name: CloudFormation Linter

on:
  pull_request:
    paths:
      - "infrastructure/**"
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  lint_cloudformation:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.x"

      - name: Install cfn-lint
        run: python -m pip install cfn-lint

      - name: Run linter
        run: cfn-lint infrastructure/template.yaml
