name: "Verify & Publish to Demo"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      refType:
        type: choice
        description: "Find branch name, commit SHA, or tag?"
        options:
          - Branch name
          - Commit SHA
          - Tag
        default: Branch name
      gitRef:
        description: "Input branch name, commit SHA, or tag"
        required: true
        type: string
        default: main

permissions:
  id-token: write
  contents: read

jobs:
  lint_infrastructure:
    name: Lint Infrastructure
    uses: ./.github/workflows/lint-cloudformation.yaml
    secrets: inherit
    with:
      gitRef: ${{ inputs.gitRef }}

  deploy_to_demo:
    permissions:
      contents: read
      id-token: write
    name: "Deploy to Demo"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - lint_infrastructure
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.9"

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@819220f63fb333a9a394dd0a5cab2d8303fd17e2 # v2

      - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
        run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.DEMO_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM validate
        working-directory: ./infrastructure
        run: sam validate

      - name: SAM build
        working-directory: ./infrastructure
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@f6188fc96fe860179f87bfc5bdeebc17eb3e1e4f # v3.9.4
        with:
          artifact-bucket-name: ${{ secrets.DEMO_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.DEMO_SIGNING_PROFILE_NAME }}
          working-directory: ./infrastructure
